<?php
/**
 * List of countries
 */

class METGS_functions_countries
{
    function __construct()
    {
        $this->countriesList= array(
            "AF" => array('name'=>"Afghanistan", 'nativename'=>"‫افغانستان"),
            "AX" => array('name'=>"Åland Islands", 'nativename'=>"Åland"),
            "AL" => array('name'=>"Albania", 'nativename'=>"Shqipëri"),
            "DZ" => array('name'=>"Algeria", 'nativename'=>"‫الجزائر"),
            "AS" => array('name'=>"American Samoa", 'nativename'=>""),
            "AD" => array('name'=>"Andorra", 'nativename'=>""),
            "AO" => array('name'=>"Angola", 'nativename'=>""),
            "AI" => array('name'=>"Anguilla", 'nativename'=>""),
            "AQ" => array('name'=>"Antarctica", 'nativename'=>""),
            "AG" => array('name'=>"Antigua and Barbuda", 'nativename'=>""),
            "AR" => array('name'=>"Argentina", 'nativename'=>""),
            "AM" => array('name'=>"Armenia", 'nativename'=>"Հայաստան"),
            "AW" => array('name'=>"Aruba", 'nativename'=>""),
            "AC" => array('name'=>"Ascension Island", 'nativename'=>""),
            "AU" => array('name'=>"Australia", 'nativename'=>""),
            "AT" => array('name'=>"Austria", 'nativename'=>"Österreich"),
            "AZ" => array('name'=>"Azerbaijan", 'nativename'=>"Azərbaycan"),
            "BS" => array('name'=>"Bahamas", 'nativename'=>""),
            "BH" => array('name'=>"Bahrain", 'nativename'=>"‫البحرين"),
            "BD" => array('name'=>"Bangladesh", 'nativename'=>"বাংলাদেশ"),
            "BB" => array('name'=>"Barbados", 'nativename'=>""),
            "BY" => array('name'=>"Belarus", 'nativename'=>"Беларусь"),
            "BE" => array('name'=>"Belgium", 'nativename'=>"België"),
            "BZ" => array('name'=>"Belize", 'nativename'=>""),
            "BJ" => array('name'=>"Benin", 'nativename'=>"Bénin"),
            "BM" => array('name'=>"Bermuda", 'nativename'=>""),
            "BT" => array('name'=>"Bhutan", 'nativename'=>"འབྲུག"),
            "BO" => array('name'=>"Bolivia", 'nativename'=>""),
            "BA" => array('name'=>"Bosnia and Herzegovina", 'nativename'=>"Босна и Херцеговина"),
            "BW" => array('name'=>"Botswana", 'nativename'=>""),
            "BV" => array('name'=>"Bouvet Island", 'nativename'=>""),
            "BR" => array('name'=>"Brazil", 'nativename'=>"Brasil"),
            "IO" => array('name'=>"British Indian Ocean Territory",'nativename'=>""),
            "VG" => array('name'=>"British Virgin Islands", 'nativename'=>""),
            "BN" => array('name'=>"Brunei", 'nativename'=>""),
            "BG" => array('name'=>"Bulgaria", 'nativename'=>"България"),
            "BF" => array('name'=>"Burkina Faso", 'nativename'=>""),
            "BI" => array('name'=>"Burundi", 'nativename'=>"Uburundi"),
            "KH" => array('name'=>"Cambodia", 'nativename'=>"កម្ពុជា"),
            "CM" => array('name'=>"Cameroon", 'nativename'=>"Cameroun"),
            "CA" => array('name'=>"Canada", 'nativename'=>""),
            "IC" => array('name'=>"Canary Islands", 'nativename'=>"islas Canarias"),
            "CV" => array('name'=>"Cape Verde", 'nativename'=>"Kabu Verdi"),
            "BQ" => array('name'=>"Caribbean Netherlands", 'nativename'=>""),
            "KY" => array('name'=>"Cayman Islands", 'nativename'=>""),
            "CF" => array('name'=>"Central African Republic",'nativename'=>"République centrafricaine"),
            "EA" => array('name'=>"Ceuta and Melilla", 'nativename'=>"Ceuta y Melilla"),
            "TD" => array('name'=>"Chad", 'nativename'=>"Tchad"),
            "CL" => array('name'=>"Chile", 'nativename'=>""),
            "CN" => array('name'=>"China", 'nativename'=>"中国"),
            "CX" => array('name'=>"Christmas Island", 'nativename'=>""),
            "CP" => array('name'=>"Clipperton Island", 'nativename'=>""),
            "CC" => array('name'=>"Cocos (Keeling) Islands", 'nativename'=>"Kepulauan Cocos (Keeling)"),
            "CO" => array('name'=>"Colombia", 'nativename'=>""),
            "KM" => array('name'=>"Comoros", 'nativename'=>"‫جزر القمر"),
            "CD" => array('name'=>"Congo (DRC)", 'nativename'=>"Jamhuri ya Kidemokrasia ya Kongo"),
            "CG" => array('name'=>"Congo (Republic)", 'nativename'=>"Congo-Brazzaville"),
            "CK" => array('name'=>"Cook Islands", 'nativename'=>""),
            "CR" => array('name'=>"Costa Rica", 'nativename'=>""),
            "CI" => array('name'=>"Côte d’Ivoire", 'nativename'=>""),
            "HR" => array('name'=>"Croatia", 'nativename'=>"Hrvatska"),
            "CU" => array('name'=>"Cuba", 'nativename'=>""),
            "CW" => array('name'=>"Curaçao", 'nativename'=>""),
            "CY" => array('name'=>"Cyprus", 'nativename'=>"Κύπρος"),
            "CZ" => array('name'=>"Czech Republic", 'nativename'=>"Česká republika"),
            "DK" => array('name'=>"Denmark", 'nativename'=>"Danmark"),
            "DG" => array('name'=>"Diego Garcia", 'nativename'=>""),
            "DJ" => array('name'=>"Djibouti", 'nativename'=>""),
            "DM" => array('name'=>"Dominica", 'nativename'=>""),
            "DO" => array('name'=>"Dominican Republic", 'nativename'=>"República Dominicana"),
            "EC" => array('name'=>"Ecuador", 'nativename'=>""),
            "EG" => array('name'=>"Egypt", 'nativename'=>"‫مصر"),
            "SV" => array('name'=>"El Salvador", 'nativename'=>""),
            "GQ" => array('name'=>"Equatorial Guinea",'nativename'=>"Guinea Ecuatorial"),
            "ER" => array('name'=>"Eritrea", 'nativename'=>""),
            "EE" => array('name'=>"Estonia", 'nativename'=>"Eesti"),
            "ET" => array('name'=>"Ethiopia", 'nativename'=>""),
            "FK" => array('name'=>"Falkland Islands", 'nativename'=>"Islas Malvinas"),
            "FO" => array('name'=>"Faroe Islands", 'nativename'=>"Føroyar"),
            "FJ" => array('name'=>"Fiji", 'nativename'=>""),
            "FI" => array('name'=>"Finland", 'nativename'=>"Suomi"),
            "FR" => array('name'=>"France", 'nativename'=>""),
            "GF" => array('name'=>"French Guiana", 'nativename'=>"Guyane française"),
            "PF" => array('name'=>"French Polynesia", 'nativename'=>"Polynésie française"),
            "TF" => array('name'=>"French Southern Territories", 'nativename'=>"Terres australes françaises"),
            "GA" => array('name'=>"Gabon", 'nativename'=>""),
            "GM" => array('name'=>"Gambia", 'nativename'=>""),
            "GE" => array('name'=>"Georgia", 'nativename'=>"საქართველო"),
            "DE" => array('name'=>"Germany", 'nativename'=>"Deutschland"),
            "GH" => array('name'=>"Ghana", 'nativename'=>"Gaana"),
            "GI" => array('name'=>"Gibraltar", 'nativename'=>""),
            "GR" => array('name'=>"Greece", 'nativename'=>"Ελλάδα"),
            "GL" => array('name'=>"Greenland", 'nativename'=>"Kalaallit Nunaat"),
            "GD" => array('name'=>"Grenada", 'nativename'=>""),
            "GP" => array('name'=>"Guadeloupe", 'nativename'=>""),
            "GU" => array('name'=>"Guam", 'nativename'=>""),
            "GT" => array('name'=>"Guatemala", 'nativename'=>""),
            "GG" => array('name'=>"Guernsey", 'nativename'=>""),
            "GN" => array('name'=>"Guinea", 'nativename'=>"Guinée"),
            "GW" => array('name'=>"Guinea-Bissau", 'nativename'=>"Guiné Bissau"),
            "GY" => array('name'=>"Guyana", 'nativename'=>""),
            "HT" => array('name'=>"Haiti", 'nativename'=>""),
            "HM" => array('name'=>"Heard & McDonald Islands", 'nativename'=>""),
            "HN" => array('name'=>"Honduras", 'nativename'=>""),
            "HK" => array('name'=>"Hong Kong", 'nativename'=>"香港"),
            "HU" => array('name'=>"Hungary", 'nativename'=>"Magyarország"),
            "IS" => array('name'=>"Iceland", 'nativename'=>"Ísland"),
            "IN" => array('name'=>"India", 'nativename'=>"भारत"),
            "ID" => array('name'=>"Indonesia", 'nativename'=>""),
            "IR" => array('name'=>"Iran", 'nativename'=>"‫ایران"),
            "IQ" => array('name'=>"Iraq", 'nativename'=>"‫العراق"),
            "IE" => array('name'=>"Ireland", 'nativename'=>""),
            "IM" => array('name'=>"Isle of Man", 'nativename'=>""),
            "IL" => array('name'=>"Israel", 'nativename'=>"‫ישראל"),
            "IT" => array('name'=>"Italy", 'nativename'=>"Italia"),
            "JM" => array('name'=>"Jamaica", 'nativename'=>""),
            "JP" => array('name'=>"Japan", 'nativename'=>"日本"),
            "JE" => array('name'=>"Jersey", 'nativename'=>""),
            "JO" => array('name'=>"Jordan", 'nativename'=>"‫الأردن"),
            "KZ" => array('name'=>"Kazakhstan", 'nativename'=>"Казахстан"),
            "KE" => array('name'=>"Kenya", 'nativename'=>""),
            "KI" => array('name'=>"Kiribati", 'nativename'=>""),
            "XK" => array('name'=>"Kosovo", 'nativename'=>"Kosovë"),
            "KW" => array('name'=>"Kuwait", 'nativename'=>"‫الكويت"),
            "KG" => array('name'=>"Kyrgyzstan", 'nativename'=>"Кыргызстан"),
            "LA" => array('name'=>"Laos", 'nativename'=>"ລາວ"),
            "LV" => array('name'=>"Latvia", 'nativename'=>"Latvija"),
            "LB" => array('name'=>"Lebanon", 'nativename'=>"‫لبنان"),
            "LS" => array('name'=>"Lesotho", 'nativename'=>""),
            "LR" => array('name'=>"Liberia", 'nativename'=>""),
            "LY" => array('name'=>"Libya", 'nativename'=>"‫ليبيا"),
            "LI" => array('name'=>"Liechtenstein", 'nativename'=>""),
            "LT" => array('name'=>"Lithuania", 'nativename'=>"Lietuva"),
            "LU" => array('name'=>"Luxembourg", 'nativename'=>""),
            "MO" => array('name'=>"Macau", 'nativename'=>"澳門"),
            "MK" => array('name'=>"Macedonia (FYROM)",'nativename'=>"Македонија"),
            "MG" => array('name'=>"Madagascar", 'nativename'=>"Madagasikara"),
            "MW" => array('name'=>"Malawi", 'nativename'=>""),
            "MY" => array('name'=>"Malaysia", 'nativename'=>""),
            "MV" => array('name'=>"Maldives", 'nativename'=>""),
            "ML" => array('name'=>"Mali", 'nativename'=>""),
            "MT" => array('name'=>"Malta", 'nativename'=>""),
            "MH" => array('name'=>"Marshall Islands", 'nativename'=>""),
            "MQ" => array('name'=>"Martinique", 'nativename'=>""),
            "MR" => array('name'=>"Mauritania", 'nativename'=>"‫موريتانيا"),
            "MU" => array('name'=>"Mauritius", 'nativename'=>"Moris"),
            "YT" => array('name'=>"Mayotte", 'nativename'=>""),
            "MX" => array('name'=>"Mexico", 'nativename'=>""),
            "FM" => array('name'=>"Micronesia", 'nativename'=>""),
            "MD" => array('name'=>"Moldova", 'nativename'=>"Republica Moldova"),
            "MC" => array('name'=>"Monaco", 'nativename'=>""),
            "MN" => array('name'=>"Mongolia", 'nativename'=>"Монгол"),
            "ME" => array('name'=>"Montenegro", 'nativename'=>"Crna Gora"),
            "MS" => array('name'=>"Montserrat", 'nativename'=>""),
            "MA" => array('name'=>"Morocco", 'nativename'=>"‫المغرب"),
            "MZ" => array('name'=>"Mozambique", 'nativename'=>"Moçambique"),
            "MM" => array('name'=>"Myanmar (Burma)", 'nativename'=>"မြန်မာ"),
            "NA" => array('name'=>"Namibia", 'nativename'=>"Namibië"),
            "NR" => array('name'=>"Nauru", 'nativename'=>""),
            "NP" => array('name'=>"Nepal", 'nativename'=>"नेपाल"),
            "NL" => array('name'=>"Netherlands", 'nativename'=>"Nederland"),
            "NC" => array('name'=>"New Caledonia", 'nativename'=>"Nouvelle-Calédonie"),
            "NZ" => array('name'=>"New Zealand", 'nativename'=>""),
            "NI" => array('name'=>"Nicaragua", 'nativename'=>""),
            "NE" => array('name'=>"Niger", 'nativename'=>"Nijar"),
            "NG" => array('name'=>"Nigeria", 'nativename'=>""),
            "NU" => array('name'=>"Niue", 'nativename'=>""),
            "NF" => array('name'=>"Norfolk Island", 'nativename'=>""),
            "MP" => array('name'=>"Northern Mariana Islands", 'nativename'=>""),
            "KP" => array('name'=>"North Korea", 'nativename'=>"조선 민주주의 인민 공화국"),
            "NO" => array('name'=>"Norway", 'nativename'=>"Norge"),
            "OM" => array('name'=>"Oman", 'nativename'=>"‫عُمان"),
            "PK" => array('name'=>"Pakistan", 'nativename'=>"‫پاکستان"),
            "PW" => array('name'=>"Palau", 'nativename'=>""),
            "PS" => array('name'=>"Palestine", 'nativename'=>"‫فلسطين"),
            "PA" => array('name'=>"Panama", 'nativename'=>""),
            "PG" => array('name'=>"Papua New Guinea", 'nativename'=>""),
            "PY" => array('name'=>"Paraguay", 'nativename'=>""),
            "PE" => array('name'=>"Peru", 'nativename'=>"Perú"),
            "PH" => array('name'=>"Philippines", 'nativename'=>""),
            "PN" => array('name'=>"Pitcairn Islands", 'nativename'=>""),
            "PL" => array('name'=>"Poland", 'nativename'=>"Polska"),
            "PT" => array('name'=>"Portugal", 'nativename'=>""),
            "PR" => array('name'=>"Puerto Rico", 'nativename'=>""),
            "QA" => array('name'=>"Qatar", 'nativename'=>"‫قطر"),
            "RE" => array('name'=>"Réunion", 'nativename'=>"La Réunion"),
            "RO" => array('name'=>"Romania", 'nativename'=>"România"),
            "RU" => array('name'=>"Russia", 'nativename'=>"Россия"),
            "RW" => array('name'=>"Rwanda", 'nativename'=>""),
            "BL" => array('name'=>"Saint Barthélemy", 'nativename'=>"Saint-Barthélemy"),
            "SH" => array('name'=>"Saint Helena", 'nativename'=>""),
            "KN" => array('name'=>"Saint Kitts and Nevis", 'nativename'=>""),
            "LC" => array('name'=>"Saint Lucia", 'nativename'=>""),
            "MF" => array('name'=>"Saint Martin", 'nativename'=>""),
            "PM" => array('name'=>"Saint Pierre and Miquelon", 'nativename'=>"Saint-Pierre-et-Miquelon"),
            "WS" => array('name'=>"Samoa", 'nativename'=>""),
            "SM" => array('name'=>"San Marino", 'nativename'=>""),
            "ST" => array('name'=>"São Tomé and Príncipe", 'nativename'=>"São Tomé e Príncipe"),
            "SA" => array('name'=>"Saudi Arabia", 'nativename'=>"‫المملكة العربية السعودية"),
            "SN" => array('name'=>"Senegal", 'nativename'=>"Sénégal"),
            "RS" => array('name'=>"Serbia", 'nativename'=>"Србија"),
            "SC" => array('name'=>"Seychelles", 'nativename'=>""),
            "SL" => array('name'=>"Sierra Leone", 'nativename'=>""),
            "SG" => array('name'=>"Singapore", 'nativename'=>""),
            "SX" => array('name'=>"Sint Maarten", 'nativename'=>""),
            "SK" => array('name'=>"Slovakia", 'nativename'=>"Slovensko"),
            "SI" => array('name'=>"Slovenia", 'nativename'=>"Slovenija"),
            "SB" => array('name'=>"Solomon Islands", 'nativename'=>""),
            "SO" => array('name'=>"Somalia", 'nativename'=>"Soomaaliya"),
            "ZA" => array('name'=>"South Africa", 'nativename'=>""),
            "GS" => array('name'=>"South Georgia & South Sandwich Islands", 'nativename'=>""),
            "KR" => array('name'=>"South Korea", 'nativename'=>"대한민국"),
            "SS" => array('name'=>"South Sudan", 'nativename'=>"‫جنوب السودان"),
            "ES" => array('name'=>"Spain", 'nativename'=>"España"),
            "LK" => array('name'=>"Sri Lanka", 'nativename'=>"ශ්‍රී ලංකාව"),
            "VC" => array('name'=>"St. Vincent & Grenadines", 'nativename'=>""),
            "SD" => array('name'=>"Sudan", 'nativename'=>"‫السودان"),
            "SR" => array('name'=>"Suriname", 'nativename'=>""),
            "SJ" => array('name'=>"Svalbard and Jan Mayen", 'nativename'=>"Svalbard og Jan Mayen"),
            "SZ" => array('name'=>"Swaziland", 'nativename'=>""),
            "SE" => array('name'=>"Sweden", 'nativename'=>"Sverige"),
            "CH" => array('name'=>"Switzerland", 'nativename'=>"Schweiz"),
            "SY" => array('name'=>"Syria", 'nativename'=>"‫سوريا"),
            "TW" => array('name'=>"Taiwan", 'nativename'=>"台灣"),
            "TJ" => array('name'=>"Tajikistan", 'nativename'=>""),
            "TZ" => array('name'=>"Tanzania", 'nativename'=>""),
            "TH" => array('name'=>"Thailand", 'nativename'=>"ไทย"),
            "TL" => array('name'=>"Timor-Leste", 'nativename'=>""),
            "TG" => array('name'=>"Togo", 'nativename'=>""),
            "TK" => array('name'=>"Tokelau", 'nativename'=>""),
            "TO" => array('name'=>"Tonga", 'nativename'=>""),
            "TT" => array('name'=>"Trinidad and Tobago", 'nativename'=>""),
            "TA" => array('name'=>"Tristan da Cunha", 'nativename'=>""),
            "TN" => array('name'=>"Tunisia", 'nativename'=>"‫تونس"),
            "TR" => array('name'=>"Turkey", 'nativename'=>"Türkiye"),
            "TM" => array('name'=>"Turkmenistan", 'nativename'=>""),
            "TC" => array('name'=>"Turks and Caicos Islands", 'nativename'=>""),
            "TV" => array('name'=>"Tuvalu", 'nativename'=>""),
            "UM" => array('name'=>"U.S. Outlying Islands", 'nativename'=>""),
            "VI" => array('name'=>"U.S. Virgin Islands", 'nativename'=>""),
            "UG" => array('name'=>"Uganda", 'nativename'=>""),
            "UA" => array('name'=>"Ukraine", 'nativename'=>"Україна"),
            "AE" => array('name'=>"United Arab Emirates", 'nativename'=>"‫الإمارات العربية المتحدة"),
            "GB" => array('name'=>"United Kingdom", 'nativename'=>""),
            "US" => array('name'=>"United States", 'nativename'=>""),
            "UY" => array('name'=>"Uruguay", 'nativename'=>""),
            "UZ" => array('name'=>"Uzbekistan", 'nativename'=>"Oʻzbekiston"),
            "VU" => array('name'=>"Vanuatu", 'nativename'=>""),
            "VA" => array('name'=>"Vatican City", 'nativename'=>"Città del Vaticano"),
            "VE" => array('name'=>"Venezuela", 'nativename'=>""),
            "VN" => array('name'=>"Vietnam", 'nativename'=>"Việt Nam"),
            "WF" => array('name'=>"Wallis and Futuna", 'nativename'=>""),
            "EH" => array('name'=>"Western Sahara", 'nativename'=>"‫الصحراء الغربية"),
            "YE" => array('name'=>"Yemen", 'nativename'=>"‫اليمن"),
            "ZM" => array('name'=>"Zambia", 'nativename'=>""),
            "ZW" => array('name'=>"Zimbabwe", 'nativename'=>"")
        );
    }
    
    function getSelectorList(){
        $selectList=array();
        foreach ($this->countriesList as $countryid => $country){
            $selectList[$countryid]=$country['name'];
            if (!empty($country['nativename'])){
                $selectList[$countryid].=' - '.$country['nativename'];
            }
        }
        return $selectList;
    }
    
    function getName($countryid){
        if(!empty($this->countriesList[$countryid]['name'])) {
            return $this->countriesList[$countryid]['name'];
        } else {
            return '';
        }
    }

    function getNativeName($countryid){
        if(!empty($this->countriesList[$countryid]['nativename'])) {
            return $this->countriesList[$countryid]['nativename'];
        } else {
            return '';
        }
    }
}